### ISSUE TITLE
redundant metric score for EmbeddingAverageCosineSimilarity

### ISSUE THREAD

**Issue by yana-xuyan** [Maluuba/nlg-eval#106]
Dear Mr./Ms.
I just found that in the printed results, EmbeddingAverageCosineSimilarity is shown twice, where there's a typo in the latter one. I'm reporting this since It's kinda annoying when I try to arrange all the experiment results.

Bleu_1: 0.143039
Bleu_2: 0.063165
Bleu_3: 0.032138
Bleu_4: 0.017839
METEOR: 0.082527
ROUGE_L: 0.138663
CIDEr: 0.176916
SkipThoughtsCosineSimilarity: 0.573908
**EmbeddingAverageCosineSimilarity: 0.816876
EmbeddingAverageCosineSimilairty: 0.816876**
VectorExtremaCosineSimilarity: 0.441681
GreedyMatchingScore: 0.708851

**Comment by juharris** [comment]
Thanks for using and providing feedback for nlg-eval! It is indeed annoying but notice that they're slightly different. This is because of a typo and for now we show both on purpose. You can see the comment here: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/word2vec/evaluate.py#L104-L106
Eventually we'll get rid of the duplicate one but we don't want to make possibly breaking changes even though this is just in a printed string, someone could be grep'ing for it or something like that.

If it's still an issue, you can see examples in the README for using the object oriented API via Python instead of the CLI and customize the output and metrics if necessary.
