### ISSUE TITLE
How many files need to be downloaded by nlg-eval --setup?

### ISSUE THREAD

**Issue by happyMinionVic** [Maluuba/nlg-eval#109]
I manually downloaded these files due to the network issue. Here I got 5 files including btable.npy, dictionary.txt, glove.6B.zip, glove2word2vec.py, utable.npy.

Are there any other files I am missing? And where should these files be?

**Comment by juharris** [comment]
Specifying where nlg-eval can find the files: https://github.com/Maluuba/nlg-eval#custom-setup
Then you should run the recommended setup because it will only download missing data files.

If you really want to see the full list, then you can infer the required files from: https://github.com/Maluuba/nlg-eval/blob/master/bin/nlg-eval#L67

**Comment by happyMinionVic** [comment]
Thank you for your timely help : )
