### ISSUE TITLE
tokenization - what type should I use

### ISSUE THREAD

**Issue by Jmallins** [Maluuba/nlg-eval#2]
I'm interested in using this library but I wondering what type of tokenization/casing I should use?

**Comment by kracwarlock** [comment]
Hi @Jmallins 

**Tokenization**
If you check the Usage section in the Readme file, we have some example files for reference.
Our code just needs the text string and then it does tokenization internally. All the embedding based metrics use `word_tokenize` from `nltk.tokenize`. All the word overlap based metrics just split on spaces currently.

**Casing**
We don't modify the input text casing. That choice is left to the user.
If your text generation model is constrained to only output lowercase, then lowercase everything before input otherwise leave it as is.

**Comment by kracwarlock** [comment]
I am closing this issue. Let us know if you have any more questions.
