### ISSUE TITLE
Question: Varying number of references

### ISSUE THREAD

**Issue by AmitMY** [Maluuba/nlg-eval#5]
#I have a corpus with varying number of references for each candidate.
Is there a way to input the evaluation with that kind of data?

If not, a solution can be to create the maximum number of references amount of files and to duplicate references when I don't have enough.

A better solution, because I don't want to save files all the time, is running
```python
compute_individual_metrics(references, hypothesis)
```
for every tuple of `(hyp, refs)`, and eventually, average them, Is that kind of thing valid? Are you somehow optimizing the batch method such that it is way faster than this? (like, are you loading the data files every time or just once)

**Comment by kracwarlock** [comment]
Hi.
 
Calling `compute_individual_metrics` is going to load the model each time which is going to be very very slow if your corpus is large. `compute_metrics` loads it only once so that is much more efficient. Your approach of creating files upto the maximum reference number is going to be much faster in that case.
 
If you are generating sentences and if loading time of the model < generation time and you can do that in parallel then calling `compute_individual_metrics` might be better. Depends on your setup. Hard to say without knowing more about it.

**Comment by AmitMY** [comment]
Thanks!
Is there a way that instead of files, I can `compute_metrics` for arrays? It's just easier to handle that way.

btw, was this system written on a unix machine? I'm having some errors in windows with the correct versions. If it is intended to work on windows as well, I'll post an issue with the errors

**Comment by kracwarlock** [comment]
We have added this functionality now and the instructions are in the updated `README.md`. The update is also pasted below for reference. The `NLGEval()` will load all the models that you require and then you can just call the `evaluate` method repeatedly. Since the models are not loaded again on each call now, this should be efficient for your use-case. Let us know if there is any other issue. Thanks for bringing this use-case to our notice!

---

### object oriented API for repeated calls in a script ###

    from nlgeval import NLGEval
    nlgeval = NLGEval()  # loads the models
    metrics_dict = nlgeval.evaluate(references, hypothesis)

where `references` is a list of ground truth reference text strings and
`hypothesis` is the hypothesis text string.

**Comment by AmitMY** [comment]
Thank you very much!
This will be very useful for my planned work

**Comment by friskit-china** [comment]
Hi @kracwarlock ,

I followed @AmitMY 's method: 

> for every tuple of (hyp, refs), and eventually, average them

However, the averaged performance is worse than evaluate on the entire hyp and ref lists (by the nlg-eval standalone command). Which one is correct?

**Comment by juharris** [comment]
I think it's because for BLEU we're using `option='closest'`: 
https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/pycocoevalcap/bleu/bleu.py#L40

Sorry I don't know which is "correct".
